CREATE TABLE account (
    id UUID PRIMARY KEY NOT NULL,
    nickname VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('CUSTOMER', 'ADMIN'))
);

CREATE TABLE schedule (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    start_at TIMESTAMP NOT NULL,
    end_at TIMESTAMP NOT NULL,
    applicants INT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELED')),
    account_id UUID NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (account_id) REFERENCES account(id)
);

CREATE TABLE schedule_slot (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_start_time TIMESTAMP NOT NULL,
    max_applicants INT NOT NULL DEFAULT 50000,
    confirmed_applicants INT NOT NULL DEFAULT 0
);
CREATE INDEX idx_schedule_slot_start_time ON schedule_slot (slot_start_time);
